#!/bin/bash

# read/write options
DIR=./build
FILE=${DIR}/vimrc
CONFIGS=./config

# prepare vimrc for writing
if [ ! -d "$DIR" ]; then
    mkdir ${DIR}
    touch ${FILE}
else 
    if [ -f "$FILE" ]; then
        rm ${FILE}
    fi

    touch ${FILE}
fi

# concat config file contents to build/vimrc
for CONFIG in ${CONFIGS}/*; do less $CONFIG >> $FILE; done

