lua utils = require('NAMESPACE/utils')
lua require('NAMESPACE/buftabline')
lua require('NAMESPACE/colourscheme')
lua require('NAMESPACE/lightline')
lua require('NAMESPACE/native')
lua require('NAMESPACE/nerdtree')
lua require('NAMESPACE/format-on-save')
lua require('NAMESPACE/bookmarks')
lua require('NAMESPACE/harpoon')
lua require('NAMESPACE/json-prettify')
lua require('NAMESPACE/phpqa')
lua require('NAMESPACE/telescope')
lua require('NAMESPACE/uuid')
lua require('NAMESPACE/easy-align')
lua require('NAMESPACE/lua-snip')
