lua utils = require('NAMESPACE/utils')
lua require('NAMESPACE/telescope')
lua require('NAMESPACE/format-on-save')
lua require('NAMESPACE/bookmarks')
lua require('NAMESPACE/obsidian')
lua require('NAMESPACE/harpoon')
lua require('NAMESPACE/dashboard')
